napvig:
  rate: 100.0
  scan_topic: /scan
  measures_pub_topic: /measures
  map_values_pub_topic: /map_values
  setpoint_pub_topic: /setpoint
  odom_topic: /odom
  map:
    measure_radius: 0.2
    smooth_radius: 0.1
    precision: 100
  napvig:
    step_ahead_size: 0.2
    gradient_step_size: 0.3
    termination_distance: 0.01
    termination_count: 25
    lookahead_horizon: 4
    algorithm: predict_collision # {predict_collision, single_step}
    min_distance: 0.15
    scatter_variance: 1 # rad
  map_test:
    range_min: -2.0
    range_max: 2.0
    range_step: 0.15
    draw: value   # {none, value, grad}
unicycle_control:
  rate: 100.0
  state_topic: /odom
  ref_topic: /setpoint
  command_topic: /cmd_vel
  gains: [0.8, 0.2, 0.13]